const parkList = [

  {
    name: "Cherokee Park",
    picture: '<img src="img/cherokee.jpg" alt="cherokee park">',
    description: "This Frederick Law Olmstead-designed park is located in the middle of the Highlands neighborhood in Louisville, Kentucky. This park offers a 2.4 mile loop for scenic driving, biking, walking or running. Park visitors will also be able to book a tee time at the golf course, bring a bow and arrow and use the archery range, or strap on their hiking boots and hit the trails.",
    biking: "Bikers that visit Cherokee Park will have several great routes to choose from. Road bikes can stick to the large, 2.4 mile loop and enjoy having a biking and pedestrian lane without worrying about cars, take one of the many exits to explore the Highlands neighborhood og Louisville, or take a trip to nearby Seneca Park. If you are riding a mountain bike, there are a plethora of trails that cut through the park and let you explore the beautiful inner trails. If riding a mountain bike, please don't use the trails if they are muddy.",
    hiking: "For a park located right in the city, the hiking that is available at Cherokee Park is great. There are 2 major trails that run through the park. The trail on the outside of the park has a lot of small hills and tree roots to climb over and the trails that run through the middle of the park are full of larger climbs. Neither of the trails lack in gorgeous scenery, but the trails in the park's interior are simply astounding with their pretty creeks and small waterfalls."
  },

  {
    name: "Carter Caves",
    picture: '<img src="img/carter-caves.jpg" alt="Carter Caves">',
    description: "Located in far eastern Kentucky, Olive Hill is home to Carter Caves State Resort Park. Visitors of Carter Caves will be able to explore 2 different caves on their own or can pay for a guided tour of a third cave. In addition to caving, there are primitive camping sites, horse trails, and hiking trails that are dotted with small cave openings and large rock features.",
    biking: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia dolor, sed tempus ligula varius gravida. Vestibulum luctus, lorem id semper gravida, nibh ante eleifend mauris, id imperdiet dolor ipsum id nisl. Sed ipsum metus, aliquam et leo sed, pretium suscipit turpis. Nullam consectetur nisi erat, nec pharetra diam mattis vel. Etiam et nisl dapibus, sodales tellus et, congue ex. Vestibulum vitae odio enim. In ac tortor aliquam, vestibulum nulla at, pulvinar mauris. Fusce vitae nibh maximus, cursus eros ut, commodo ligula. Donec ac tellus non nulla tempus volutpat at ut urna. Suspendisse placerat ante augue. Suspendisse id ligula sit amet elit fringilla facilisis. Donec semper massa libero, id facilisis felis auctor eget. In at erat arcu. In varius varius interdum.',
    hiking: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia dolor, sed tempus ligula varius gravida. Vestibulum luctus, lorem id semper gravida, nibh ante eleifend mauris, id imperdiet dolor ipsum id nisl. Sed ipsum metus, aliquam et leo sed, pretium suscipit turpis. Nullam consectetur nisi erat, nec pharetra diam mattis vel. Etiam et nisl dapibus, sodales tellus et, congue ex. Vestibulum vitae odio enim. In ac tortor aliquam, vestibulum nulla at, pulvinar mauris. Fusce vitae nibh maximus, cursus eros ut, commodo ligula. Donec ac tellus non nulla tempus volutpat at ut urna. Suspendisse placerat ante augue. Suspendisse id ligula sit amet elit fringilla facilisis. Donec semper massa libero, id facilisis felis auctor eget. In at erat arcu. In varius varius interdum.',
    camping: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia dolor, sed tempus ligula varius gravida. Vestibulum luctus, lorem id semper gravida, nibh ante eleifend mauris, id imperdiet dolor ipsum id nisl. Sed ipsum metus, aliquam et leo sed, pretium suscipit turpis. Nullam consectetur nisi erat, nec pharetra diam mattis vel. Etiam et nisl dapibus, sodales tellus et, congue ex. Vestibulum vitae odio enim. In ac tortor aliquam, vestibulum nulla at, pulvinar mauris. Fusce vitae nibh maximus, cursus eros ut, commodo ligula. Donec ac tellus non nulla tempus volutpat at ut urna. Suspendisse placerat ante augue. Suspendisse id ligula sit amet elit fringilla facilisis. Donec semper massa libero, id facilisis felis auctor eget. In at erat arcu. In varius varius interdum.'
  },

  {
    name: "Mammoth Cave National Park",
    picture: '<img src="img/mammoth-cave.jpg" alt="Mammoth Cave National Park">',
    description: "Mammoth Cave National Park is in Bowling Green Kentucky. Mammoth Cave is the longest cave system in the world and consists of chambers and subterranean passageways. Sites include the Frozen Niagara section, known for waterfall-like flowstone formations, and Gothic Avenue, its ceiling covered in 19th-century visitors’ signatures. Trails take in other park features like the Green and Nolin rivers and the sinkholes of Cedar Sink.",
    biking: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia dolor, sed tempus ligula varius gravida. Vestibulum luctus, lorem id semper gravida, nibh ante eleifend mauris, id imperdiet dolor ipsum id nisl. Sed ipsum metus, aliquam et leo sed, pretium suscipit turpis. Nullam consectetur nisi erat, nec pharetra diam mattis vel. Etiam et nisl dapibus, sodales tellus et, congue ex. Vestibulum vitae odio enim. In ac tortor aliquam, vestibulum nulla at, pulvinar mauris. Fusce vitae nibh maximus, cursus eros ut, commodo ligula. Donec ac tellus non nulla tempus volutpat at ut urna. Suspendisse placerat ante augue. Suspendisse id ligula sit amet elit fringilla facilisis. Donec semper massa libero, id facilisis felis auctor eget. In at erat arcu. In varius varius interdum.',
    camping: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum lacinia dolor, sed tempus ligula varius gravida. Vestibulum luctus, lorem id semper gravida, nibh ante eleifend mauris, id imperdiet dolor ipsum id nisl. Sed ipsum metus, aliquam et leo sed, pretium suscipit turpis. Nullam consectetur nisi erat, nec pharetra diam mattis vel. Etiam et nisl dapibus, sodales tellus et, congue ex. Vestibulum vitae odio enim. In ac tortor aliquam, vestibulum nulla at, pulvinar mauris. Fusce vitae nibh maximus, cursus eros ut, commodo ligula. Donec ac tellus non nulla tempus volutpat at ut urna. Suspendisse placerat ante augue. Suspendisse id ligula sit amet elit fringilla facilisis. Donec semper massa libero, id facilisis felis auctor eget. In at erat arcu. In varius varius interdum.'
  },

  {
    name: "Dale Hollow Lake",
    picture: '<img src="img/dale-hollow.jpg" alt ="dale hollow lake">',
    description: "Dale Hollow Lake State Resort Park is located in south-central Kentucky in the Cumberland River basin on the Obey River. The huge reservoir created by Dale Hollow Dam covers 27,700 acres in parts of Clinton and Cumberland Counties in Kentucky and Clay, Fentress, Overton, and Pickett Counties  in Tennessee. Dale Hollow Dam and Reservoir control the runoff drainage area of 935 square miles."
  }

];
