const parkList = [

  {
    name: "Cherokee Park",
    picture: '<img src="img/cherokee.jpg" alt="cherokee park">',
    description: "This Frederick Law Olmstead-designed park is located in the middle of the Highlands neighborhood in Louisville, Kentucky. This park offers a 2.4 mile loop for scenic driving, biking, walking or running. Park visitors will also be able to book a tee time at the golf course, bring a bow and arrow and use the archery range, or strap on their hiking boots and hit the trails.",
    biking: "Bikers that visit Cherokee Park will have several great routes to choose from. Road bikes can stick to the large, 2.4 mile loop and enjoy having a biking and pedestrian lane without worrying about cars, take one of the many exits to explore the Highlands neighborhood og Louisville, or take a trip to nearby Seneca Park. If you are riding a mountain bike, there are a plethora of trails that cut through the park and let you explore the beautiful inner trails. If riding a mountain bike, please don't use the trails if they are muddy.",
    hiking: "For a park located right in the city, the hiking that is available at Cherokee Park is great. There are 2 major trails that run through the park. The trail on the outside of the park has a lot of small hills and tree roots to climb over and the trails that run through the middle of the park are full of larger climbs. Neither of the trails lack in gorgeous scenery, but the trails in the park's interior are simply astounding with their pretty creeks and small waterfalls."
  },

  {
    name: "Carter Caves",
    picture: '<img src="img/carter-caves.jpg" alt="Carter Caves">',
    description: "Located in far eastern Kentucky, Olive Hill is home to Carter Caves State Resort Park. Visitors of Carter Caves will be able to explore 2 different caves on their own or can pay for a guided tour of a third cave. In addition to caving, there are primitive camping sites, horse trails, and hiking trails that are dotted with small cave openings and large rock features.",
    hiking: 'Discover the above ground beauty of Carter Caves on 26 miles of wooded nature trails. Trails range from easy to difficult hiking level ability. The Kiser Hollow Trail, 10 miles, and the newly developed Cave Branch Loop Trail, 2 miles, are multi use trails for horseback riding, mountain biking and hiking. Guests bring and ride mountain bikes. No ATVs allowed, and no overnight camping on the trail.',
    camping: 'Enjoy the great outdoors! The campground features 89 campsites with utilities, 8 equestrian campsites with utilities, and 30 tent sites without utilities. Two bunkhouses with six wooden bunk beds and electric give those without tents or RV an opportunity to "rough it" (bring your own bedding/linens). A dump station, and three central service buildings with rest rooms and showers available for campers use. November 28, 2016 - March 31, 2017: Horse Campground open with full hook ups (Water, Electric, and Sewer) available at regular price. Campground will be open but with no water available. Electric and Sewer (on sites available) will be available for discounted winter prices. Call park for pricing: 606-286-4411.'
  },

  {
    name: "Mammoth Cave National Park",
    picture: '<img src="img/mammoth-cave.jpg" alt="Mammoth Cave National Park">',
    description: "Mammoth Cave National Park is in Bowling Green Kentucky. Mammoth Cave is the longest cave system in the world and consists of chambers and subterranean passageways. Sites include the Frozen Niagara section, known for waterfall-like flowstone formations, and Gothic Avenue, its ceiling covered in 19th-century visitors’ signatures. Trails take in other park features like the Green and Nolin rivers and the sinkholes of Cedar Sink.",
    biking: 'Mammoth Cave National Park offers several opportunities for bicyclists to get out into the outdoors. Street bicycles are permitted on all paved Park roads that are open to the public, and mountain bikes are permitted on the unpaved administrative roads. In addition, certain trails have been specifically designed or designated for off-road bicycle use, and more are under development. There are many different biking opportunities in Mammoth Cave National Park, but the off-road bicycling areas are what make the park shine. My favorite is the Mammoth Cave Railroad Hike and Bike Trail, which lets you explore an old railroad.',
    hiking:"Mammoth Cave National Park is a place for letting your feet lead you – or your horse's hooves, or the tread of your bike's tires. With nearly 84 miles of trail in the backcountry, frontcountry and Visitor Center areas combined, from easy to rugged, you're certain to find just the one-on-one with nature you're looking for. Six trailheads, at Maple Springs, Lincoln, Big Hollow, First Creek, Temple Hill and White Oak give access to the backcountry's 65.8 miles of trail. Most backcountry trails are for pedestrian and horseback use only, with the exception of Big Hollow Trail, which is for pedestrian and mountain bike use only, and Maple Springs Trail and White Oak Trail, which are all-use trails.",
    camping: "Located ¼ mile from the park Visitor Center, Mammoth Cave Campground is the park's developed camping area, situating campers most conveniently for excursions underground, around the Visitor Center, on the rivers, or farther afield. Rangers on duty in the campground kiosk are happy to provide information to make your stay a special adventure. The campground's 105 sites are open seasonally and are available by reservation."
  },

  {
    name: "Dale Hollow Lake",
    picture: '<img src="img/dale-hollow.jpg" alt ="dale hollow lake">',
    description: "Dale Hollow Lake State Resort Park is located in south-central Kentucky in the Cumberland River basin on the Obey River. The huge reservoir created by Dale Hollow Dam covers 27,700 acres in parts of Clinton and Cumberland Counties in Kentucky and Clay, Fentress, Overton, and Pickett Counties  in Tennessee. Dale Hollow Dam and Reservoir control the runoff drainage area of 935 square miles.",
    biking: "Dale Hollow Lake Resort’s 3,400 acres give plenty of room for approved mountain bike trails. Bring your own bikes.",
    camping:"Thousands of acres of pristine forest insulate the 145-site campground from the cares and hassles of the everyday world (utility hookups are available). Twenty four of these campsites are set aside for campers with horses, and a new country store is located at the entrance to the campground just beside the miniature golf. Here you will find grocery items, toiletries, souvenirs, supplies, and firewood. WiFi available. Open seasonally, with campground. Don't have a tent or RV of your own? Six new camping cabins with bunks and air conditioning are available for anyone looking for a camp experience. Save yours by making a reservation today! For your convenience, a dump station and central service buildings with showers and rest rooms are offered. A pool sits inside the campround and is normally open Memorial Day weekend through Labor Day weekend.",
    hiking:"Over 15 miles of trails are designated as multi-purpose trails, open for hiking, horseback riding, and mountain biking unless otherwise posted. No motorized uses are allowed. The trails generally follow old logging roads along narrow ridge tops through the park. Most of the trails end at the tips of these ridges which form peninsulas into Dale Hollow Lake, requiring a return trip on the same trail."
  },

  {
    name: "Cumberland Falls State Resort Park",
    picture: '<img src="img/cumberland-falls.jpg">',
    description: "Cumberland Falls State Resort Park is located in the same town as the original Kentucky Fried Chicked: Corbin, KY. Just 15 miles from the Colonel's restaurant is the waterfall with the largest flow of any in the state. Cumberland Falls is not only a sight to see during the day, but also at night. Cumberland Falls is the only waterfall in the United States that can display the rare moonbow. On really clear, full-mooned evenings, Cumberland Falls large mist spray will refract the light perfectly to create a rainbow &mdash; IN THE MIDDLE OF THE NIGHT!",
    camping: "Enjoy the great outdoors in the campground, featuring 50 campsites with electric and water hookups. The campground has a central service building with showers and rest rooms, a grocery, and a dump station. Pets are allowed if restrained. Closed for season from November 15 to March 15.",
    hiking: "Cumberland Falls is a hiker’s paradise with 17 miles of hiking trails that wind through the park to scenic areas. The Moonbow Trail connects with many backpacking trails in the Daniel Boone National Forest. Pets are not permitted within the McCreary County side of Cumberland Falls State Resort Park as this area is within a dedicated Kentucky State Nature Preserve. Note: Cumberlad Falls is a special part of my childhood, and I would be remiss not to tell you about nearby Eagle Falls, which is one of the most amazing hikes in the state."
  }

];
